// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/getamis/alice/crypto/tss/signer/message.proto

package signer

import (
	fmt "fmt"
	commitment "github.com/getamis/alice/crypto/commitment"
	oprf "github.com/getamis/alice/crypto/oprf"
	zkproof "github.com/getamis/alice/crypto/zkproof"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_Pubkey       Type = 0
	Type_EncK         Type = 1
	Type_Mta          Type = 2
	Type_Delta        Type = 3
	Type_ProofAi      Type = 4
	Type_CommitViAi   Type = 5
	Type_DecommitViAi Type = 6
	Type_CommitUiTi   Type = 7
	Type_DecommitUiTi Type = 8
	Type_Si           Type = 9
	// For OPRF
	Type_OPRFRequest  Type = 10
	Type_OPRFResponse Type = 11
)

var Type_name = map[int32]string{
	0:  "Pubkey",
	1:  "EncK",
	2:  "Mta",
	3:  "Delta",
	4:  "ProofAi",
	5:  "CommitViAi",
	6:  "DecommitViAi",
	7:  "CommitUiTi",
	8:  "DecommitUiTi",
	9:  "Si",
	10: "OPRFRequest",
	11: "OPRFResponse",
}

var Type_value = map[string]int32{
	"Pubkey":       0,
	"EncK":         1,
	"Mta":          2,
	"Delta":        3,
	"ProofAi":      4,
	"CommitViAi":   5,
	"DecommitViAi": 6,
	"CommitUiTi":   7,
	"DecommitUiTi": 8,
	"Si":           9,
	"OPRFRequest":  10,
	"OPRFResponse": 11,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad801314df39a0f8, []int{0}
}

type Message struct {
	Type Type   `protobuf:"varint,1,opt,name=type,proto3,enum=signer.Type" json:"type,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Body:
	//	*Message_Pubkey
	//	*Message_EncK
	//	*Message_Mta
	//	*Message_Delta
	//	*Message_ProofAi
	//	*Message_CommitViAi
	//	*Message_DecommitViAi
	//	*Message_CommitUiTi
	//	*Message_DecommitUiTi
	//	*Message_Si
	//	*Message_OprfRequest
	//	*Message_OprfResponse
	Body                 isMessage_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad801314df39a0f8, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_Pubkey
}

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type isMessage_Body interface {
	isMessage_Body()
}

type Message_Pubkey struct {
	Pubkey *BodyPublicKey `protobuf:"bytes,3,opt,name=pubkey,proto3,oneof"`
}

type Message_EncK struct {
	EncK *BodyEncK `protobuf:"bytes,4,opt,name=encK,proto3,oneof"`
}

type Message_Mta struct {
	Mta *BodyMta `protobuf:"bytes,5,opt,name=mta,proto3,oneof"`
}

type Message_Delta struct {
	Delta *BodyDelta `protobuf:"bytes,6,opt,name=delta,proto3,oneof"`
}

type Message_ProofAi struct {
	ProofAi *BodyProofAi `protobuf:"bytes,7,opt,name=proofAi,proto3,oneof"`
}

type Message_CommitViAi struct {
	CommitViAi *BodyCommitViAi `protobuf:"bytes,8,opt,name=commitViAi,proto3,oneof"`
}

type Message_DecommitViAi struct {
	DecommitViAi *BodyDecommitViAi `protobuf:"bytes,9,opt,name=decommitViAi,proto3,oneof"`
}

type Message_CommitUiTi struct {
	CommitUiTi *BodyCommitUiTi `protobuf:"bytes,10,opt,name=commitUiTi,proto3,oneof"`
}

type Message_DecommitUiTi struct {
	DecommitUiTi *BodyDecommitUiTi `protobuf:"bytes,11,opt,name=decommitUiTi,proto3,oneof"`
}

type Message_Si struct {
	Si *BodySi `protobuf:"bytes,12,opt,name=si,proto3,oneof"`
}

type Message_OprfRequest struct {
	OprfRequest *oprf.OprfRequestMessage `protobuf:"bytes,13,opt,name=oprfRequest,proto3,oneof"`
}

type Message_OprfResponse struct {
	OprfResponse *oprf.OprfResponseMessage `protobuf:"bytes,14,opt,name=oprfResponse,proto3,oneof"`
}

func (*Message_Pubkey) isMessage_Body() {}

func (*Message_EncK) isMessage_Body() {}

func (*Message_Mta) isMessage_Body() {}

func (*Message_Delta) isMessage_Body() {}

func (*Message_ProofAi) isMessage_Body() {}

func (*Message_CommitViAi) isMessage_Body() {}

func (*Message_DecommitViAi) isMessage_Body() {}

func (*Message_CommitUiTi) isMessage_Body() {}

func (*Message_DecommitUiTi) isMessage_Body() {}

func (*Message_Si) isMessage_Body() {}

func (*Message_OprfRequest) isMessage_Body() {}

func (*Message_OprfResponse) isMessage_Body() {}

func (m *Message) GetBody() isMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Message) GetPubkey() *BodyPublicKey {
	if x, ok := m.GetBody().(*Message_Pubkey); ok {
		return x.Pubkey
	}
	return nil
}

func (m *Message) GetEncK() *BodyEncK {
	if x, ok := m.GetBody().(*Message_EncK); ok {
		return x.EncK
	}
	return nil
}

func (m *Message) GetMta() *BodyMta {
	if x, ok := m.GetBody().(*Message_Mta); ok {
		return x.Mta
	}
	return nil
}

func (m *Message) GetDelta() *BodyDelta {
	if x, ok := m.GetBody().(*Message_Delta); ok {
		return x.Delta
	}
	return nil
}

func (m *Message) GetProofAi() *BodyProofAi {
	if x, ok := m.GetBody().(*Message_ProofAi); ok {
		return x.ProofAi
	}
	return nil
}

func (m *Message) GetCommitViAi() *BodyCommitViAi {
	if x, ok := m.GetBody().(*Message_CommitViAi); ok {
		return x.CommitViAi
	}
	return nil
}

func (m *Message) GetDecommitViAi() *BodyDecommitViAi {
	if x, ok := m.GetBody().(*Message_DecommitViAi); ok {
		return x.DecommitViAi
	}
	return nil
}

func (m *Message) GetCommitUiTi() *BodyCommitUiTi {
	if x, ok := m.GetBody().(*Message_CommitUiTi); ok {
		return x.CommitUiTi
	}
	return nil
}

func (m *Message) GetDecommitUiTi() *BodyDecommitUiTi {
	if x, ok := m.GetBody().(*Message_DecommitUiTi); ok {
		return x.DecommitUiTi
	}
	return nil
}

func (m *Message) GetSi() *BodySi {
	if x, ok := m.GetBody().(*Message_Si); ok {
		return x.Si
	}
	return nil
}

func (m *Message) GetOprfRequest() *oprf.OprfRequestMessage {
	if x, ok := m.GetBody().(*Message_OprfRequest); ok {
		return x.OprfRequest
	}
	return nil
}

func (m *Message) GetOprfResponse() *oprf.OprfResponseMessage {
	if x, ok := m.GetBody().(*Message_OprfResponse); ok {
		return x.OprfResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_Pubkey)(nil),
		(*Message_EncK)(nil),
		(*Message_Mta)(nil),
		(*Message_Delta)(nil),
		(*Message_ProofAi)(nil),
		(*Message_CommitViAi)(nil),
		(*Message_DecommitViAi)(nil),
		(*Message_CommitUiTi)(nil),
		(*Message_DecommitUiTi)(nil),
		(*Message_Si)(nil),
		(*Message_OprfRequest)(nil),
		(*Message_OprfResponse)(nil),
	}
}

type BodyPublicKey struct {
	Pubkey               []byte                            `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	AgCommitment         *commitment.HashCommitmentMessage `protobuf:"bytes,3,opt,name=agCommitment,proto3" json:"agCommitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *BodyPublicKey) Reset()         { *m = BodyPublicKey{} }
func (m *BodyPublicKey) String() string { return proto.CompactTextString(m) }
func (*BodyPublicKey) ProtoMessage()    {}
func (*BodyPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad801314df39a0f8, []int{1}
}

func (m *BodyPublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BodyPublicKey.Unmarshal(m, b)
}
func (m *BodyPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BodyPublicKey.Marshal(b, m, deterministic)
}
func (m *BodyPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BodyPublicKey.Merge(m, src)
}
func (m *BodyPublicKey) XXX_Size() int {
	return xxx_messageInfo_BodyPublicKey.Size(m)
}
func (m *BodyPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_BodyPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_BodyPublicKey proto.InternalMessageInfo

func (m *BodyPublicKey) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *BodyPublicKey) GetAgCommitment() *commitment.HashCommitmentMessage {
	if m != nil {
		return m.AgCommitment
	}
	return nil
}

type BodyEncK struct {
	Enck                 []byte   `protobuf:"bytes,2,opt,name=enck,proto3" json:"enck,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BodyEncK) Reset()         { *m = BodyEncK{} }
func (m *BodyEncK) String() string { return proto.CompactTextString(m) }
func (*BodyEncK) ProtoMessage()    {}
func (*BodyEncK) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad801314df39a0f8, []int{2}
}

func (m *BodyEncK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BodyEncK.Unmarshal(m, b)
}
func (m *BodyEncK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BodyEncK.Marshal(b, m, deterministic)
}
func (m *BodyEncK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BodyEncK.Merge(m, src)
}
func (m *BodyEncK) XXX_Size() int {
	return xxx_messageInfo_BodyEncK.Size(m)
}
func (m *BodyEncK) XXX_DiscardUnknown() {
	xxx_messageInfo_BodyEncK.DiscardUnknown(m)
}

var xxx_messageInfo_BodyEncK proto.InternalMessageInfo

func (m *BodyEncK) GetEnck() []byte {
	if m != nil {
		return m.Enck
	}
	return nil
}

type BodyMta struct {
	EncAiAlpha           []byte   `protobuf:"bytes,1,opt,name=encAiAlpha,proto3" json:"encAiAlpha,omitempty"`
	EncWiAlpha           []byte   `protobuf:"bytes,2,opt,name=encWiAlpha,proto3" json:"encWiAlpha,omitempty"`
	WiProof              []byte   `protobuf:"bytes,3,opt,name=wiProof,proto3" json:"wiProof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BodyMta) Reset()         { *m = BodyMta{} }
func (m *BodyMta) String() string { return proto.CompactTextString(m) }
func (*BodyMta) ProtoMessage()    {}
func (*BodyMta) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad801314df39a0f8, []int{3}
}

func (m *BodyMta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BodyMta.Unmarshal(m, b)
}
func (m *BodyMta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BodyMta.Marshal(b, m, deterministic)
}
func (m *BodyMta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BodyMta.Merge(m, src)
}
func (m *BodyMta) XXX_Size() int {
	return xxx_messageInfo_BodyMta.Size(m)
}
func (m *BodyMta) XXX_DiscardUnknown() {
	xxx_messageInfo_BodyMta.DiscardUnknown(m)
}

var xxx_messageInfo_BodyMta proto.InternalMessageInfo

func (m *BodyMta) GetEncAiAlpha() []byte {
	if m != nil {
		return m.EncAiAlpha
	}
	return nil
}

func (m *BodyMta) GetEncWiAlpha() []byte {
	if m != nil {
		return m.EncWiAlpha
	}
	return nil
}

func (m *BodyMta) GetWiProof() []byte {
	if m != nil {
		return m.WiProof
	}
	return nil
}

type BodyDelta struct {
	Delta                []byte   `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BodyDelta) Reset()         { *m = BodyDelta{} }
func (m *BodyDelta) String() string { return proto.CompactTextString(m) }
func (*BodyDelta) ProtoMessage()    {}
func (*BodyDelta) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad801314df39a0f8, []int{4}
}

func (m *BodyDelta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BodyDelta.Unmarshal(m, b)
}
func (m *BodyDelta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BodyDelta.Marshal(b, m, deterministic)
}
func (m *BodyDelta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BodyDelta.Merge(m, src)
}
func (m *BodyDelta) XXX_Size() int {
	return xxx_messageInfo_BodyDelta.Size(m)
}
func (m *BodyDelta) XXX_DiscardUnknown() {
	xxx_messageInfo_BodyDelta.DiscardUnknown(m)
}

var xxx_messageInfo_BodyDelta proto.InternalMessageInfo

func (m *BodyDelta) GetDelta() []byte {
	if m != nil {
		return m.Delta
	}
	return nil
}

type BodyProofAi struct {
	AgDecommitment       *commitment.HashDecommitmentMessage `protobuf:"bytes,1,opt,name=agDecommitment,proto3" json:"agDecommitment,omitempty"`
	AiProof              *zkproof.SchnorrProofMessage        `protobuf:"bytes,2,opt,name=aiProof,proto3" json:"aiProof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *BodyProofAi) Reset()         { *m = BodyProofAi{} }
func (m *BodyProofAi) String() string { return proto.CompactTextString(m) }
func (*BodyProofAi) ProtoMessage()    {}
func (*BodyProofAi) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad801314df39a0f8, []int{5}
}

func (m *BodyProofAi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BodyProofAi.Unmarshal(m, b)
}
func (m *BodyProofAi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BodyProofAi.Marshal(b, m, deterministic)
}
func (m *BodyProofAi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BodyProofAi.Merge(m, src)
}
func (m *BodyProofAi) XXX_Size() int {
	return xxx_messageInfo_BodyProofAi.Size(m)
}
func (m *BodyProofAi) XXX_DiscardUnknown() {
	xxx_messageInfo_BodyProofAi.DiscardUnknown(m)
}

var xxx_messageInfo_BodyProofAi proto.InternalMessageInfo

func (m *BodyProofAi) GetAgDecommitment() *commitment.HashDecommitmentMessage {
	if m != nil {
		return m.AgDecommitment
	}
	return nil
}

func (m *BodyProofAi) GetAiProof() *zkproof.SchnorrProofMessage {
	if m != nil {
		return m.AiProof
	}
	return nil
}

type BodyCommitViAi struct {
	ViCommitment         *commitment.HashCommitmentMessage `protobuf:"bytes,1,opt,name=viCommitment,proto3" json:"viCommitment,omitempty"`
	AiCommitment         *commitment.HashCommitmentMessage `protobuf:"bytes,2,opt,name=aiCommitment,proto3" json:"aiCommitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *BodyCommitViAi) Reset()         { *m = BodyCommitViAi{} }
func (m *BodyCommitViAi) String() string { return proto.CompactTextString(m) }
func (*BodyCommitViAi) ProtoMessage()    {}
func (*BodyCommitViAi) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad801314df39a0f8, []int{6}
}

func (m *BodyCommitViAi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BodyCommitViAi.Unmarshal(m, b)
}
func (m *BodyCommitViAi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BodyCommitViAi.Marshal(b, m, deterministic)
}
func (m *BodyCommitViAi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BodyCommitViAi.Merge(m, src)
}
func (m *BodyCommitViAi) XXX_Size() int {
	return xxx_messageInfo_BodyCommitViAi.Size(m)
}
func (m *BodyCommitViAi) XXX_DiscardUnknown() {
	xxx_messageInfo_BodyCommitViAi.DiscardUnknown(m)
}

var xxx_messageInfo_BodyCommitViAi proto.InternalMessageInfo

func (m *BodyCommitViAi) GetViCommitment() *commitment.HashCommitmentMessage {
	if m != nil {
		return m.ViCommitment
	}
	return nil
}

func (m *BodyCommitViAi) GetAiCommitment() *commitment.HashCommitmentMessage {
	if m != nil {
		return m.AiCommitment
	}
	return nil
}

type BodyDecommitViAi struct {
	ViDecommitment       *commitment.HashDecommitmentMessage `protobuf:"bytes,1,opt,name=viDecommitment,proto3" json:"viDecommitment,omitempty"`
	AiDecommitment       *commitment.HashDecommitmentMessage `protobuf:"bytes,2,opt,name=aiDecommitment,proto3" json:"aiDecommitment,omitempty"`
	RhoIProof            *zkproof.SchnorrProofMessage        `protobuf:"bytes,3,opt,name=rhoIProof,proto3" json:"rhoIProof,omitempty"`
	LiProof              *zkproof.SchnorrProofMessage        `protobuf:"bytes,4,opt,name=liProof,proto3" json:"liProof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *BodyDecommitViAi) Reset()         { *m = BodyDecommitViAi{} }
func (m *BodyDecommitViAi) String() string { return proto.CompactTextString(m) }
func (*BodyDecommitViAi) ProtoMessage()    {}
func (*BodyDecommitViAi) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad801314df39a0f8, []int{7}
}

func (m *BodyDecommitViAi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BodyDecommitViAi.Unmarshal(m, b)
}
func (m *BodyDecommitViAi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BodyDecommitViAi.Marshal(b, m, deterministic)
}
func (m *BodyDecommitViAi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BodyDecommitViAi.Merge(m, src)
}
func (m *BodyDecommitViAi) XXX_Size() int {
	return xxx_messageInfo_BodyDecommitViAi.Size(m)
}
func (m *BodyDecommitViAi) XXX_DiscardUnknown() {
	xxx_messageInfo_BodyDecommitViAi.DiscardUnknown(m)
}

var xxx_messageInfo_BodyDecommitViAi proto.InternalMessageInfo

func (m *BodyDecommitViAi) GetViDecommitment() *commitment.HashDecommitmentMessage {
	if m != nil {
		return m.ViDecommitment
	}
	return nil
}

func (m *BodyDecommitViAi) GetAiDecommitment() *commitment.HashDecommitmentMessage {
	if m != nil {
		return m.AiDecommitment
	}
	return nil
}

func (m *BodyDecommitViAi) GetRhoIProof() *zkproof.SchnorrProofMessage {
	if m != nil {
		return m.RhoIProof
	}
	return nil
}

func (m *BodyDecommitViAi) GetLiProof() *zkproof.SchnorrProofMessage {
	if m != nil {
		return m.LiProof
	}
	return nil
}

type BodyCommitUiTi struct {
	UiCommitment         *commitment.HashCommitmentMessage `protobuf:"bytes,1,opt,name=uiCommitment,proto3" json:"uiCommitment,omitempty"`
	TiCommitment         *commitment.HashCommitmentMessage `protobuf:"bytes,2,opt,name=tiCommitment,proto3" json:"tiCommitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *BodyCommitUiTi) Reset()         { *m = BodyCommitUiTi{} }
func (m *BodyCommitUiTi) String() string { return proto.CompactTextString(m) }
func (*BodyCommitUiTi) ProtoMessage()    {}
func (*BodyCommitUiTi) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad801314df39a0f8, []int{8}
}

func (m *BodyCommitUiTi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BodyCommitUiTi.Unmarshal(m, b)
}
func (m *BodyCommitUiTi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BodyCommitUiTi.Marshal(b, m, deterministic)
}
func (m *BodyCommitUiTi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BodyCommitUiTi.Merge(m, src)
}
func (m *BodyCommitUiTi) XXX_Size() int {
	return xxx_messageInfo_BodyCommitUiTi.Size(m)
}
func (m *BodyCommitUiTi) XXX_DiscardUnknown() {
	xxx_messageInfo_BodyCommitUiTi.DiscardUnknown(m)
}

var xxx_messageInfo_BodyCommitUiTi proto.InternalMessageInfo

func (m *BodyCommitUiTi) GetUiCommitment() *commitment.HashCommitmentMessage {
	if m != nil {
		return m.UiCommitment
	}
	return nil
}

func (m *BodyCommitUiTi) GetTiCommitment() *commitment.HashCommitmentMessage {
	if m != nil {
		return m.TiCommitment
	}
	return nil
}

type BodyDecommitUiTi struct {
	UiDecommitment       *commitment.HashDecommitmentMessage `protobuf:"bytes,1,opt,name=uiDecommitment,proto3" json:"uiDecommitment,omitempty"`
	TiDecommitment       *commitment.HashDecommitmentMessage `protobuf:"bytes,2,opt,name=tiDecommitment,proto3" json:"tiDecommitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *BodyDecommitUiTi) Reset()         { *m = BodyDecommitUiTi{} }
func (m *BodyDecommitUiTi) String() string { return proto.CompactTextString(m) }
func (*BodyDecommitUiTi) ProtoMessage()    {}
func (*BodyDecommitUiTi) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad801314df39a0f8, []int{9}
}

func (m *BodyDecommitUiTi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BodyDecommitUiTi.Unmarshal(m, b)
}
func (m *BodyDecommitUiTi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BodyDecommitUiTi.Marshal(b, m, deterministic)
}
func (m *BodyDecommitUiTi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BodyDecommitUiTi.Merge(m, src)
}
func (m *BodyDecommitUiTi) XXX_Size() int {
	return xxx_messageInfo_BodyDecommitUiTi.Size(m)
}
func (m *BodyDecommitUiTi) XXX_DiscardUnknown() {
	xxx_messageInfo_BodyDecommitUiTi.DiscardUnknown(m)
}

var xxx_messageInfo_BodyDecommitUiTi proto.InternalMessageInfo

func (m *BodyDecommitUiTi) GetUiDecommitment() *commitment.HashDecommitmentMessage {
	if m != nil {
		return m.UiDecommitment
	}
	return nil
}

func (m *BodyDecommitUiTi) GetTiDecommitment() *commitment.HashDecommitmentMessage {
	if m != nil {
		return m.TiDecommitment
	}
	return nil
}

type BodySi struct {
	Si                   []byte   `protobuf:"bytes,1,opt,name=si,proto3" json:"si,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BodySi) Reset()         { *m = BodySi{} }
func (m *BodySi) String() string { return proto.CompactTextString(m) }
func (*BodySi) ProtoMessage()    {}
func (*BodySi) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad801314df39a0f8, []int{10}
}

func (m *BodySi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BodySi.Unmarshal(m, b)
}
func (m *BodySi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BodySi.Marshal(b, m, deterministic)
}
func (m *BodySi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BodySi.Merge(m, src)
}
func (m *BodySi) XXX_Size() int {
	return xxx_messageInfo_BodySi.Size(m)
}
func (m *BodySi) XXX_DiscardUnknown() {
	xxx_messageInfo_BodySi.DiscardUnknown(m)
}

var xxx_messageInfo_BodySi proto.InternalMessageInfo

func (m *BodySi) GetSi() []byte {
	if m != nil {
		return m.Si
	}
	return nil
}

func init() {
	proto.RegisterEnum("signer.Type", Type_name, Type_value)
	proto.RegisterType((*Message)(nil), "signer.Message")
	proto.RegisterType((*BodyPublicKey)(nil), "signer.BodyPublicKey")
	proto.RegisterType((*BodyEncK)(nil), "signer.BodyEncK")
	proto.RegisterType((*BodyMta)(nil), "signer.BodyMta")
	proto.RegisterType((*BodyDelta)(nil), "signer.BodyDelta")
	proto.RegisterType((*BodyProofAi)(nil), "signer.BodyProofAi")
	proto.RegisterType((*BodyCommitViAi)(nil), "signer.BodyCommitViAi")
	proto.RegisterType((*BodyDecommitViAi)(nil), "signer.BodyDecommitViAi")
	proto.RegisterType((*BodyCommitUiTi)(nil), "signer.BodyCommitUiTi")
	proto.RegisterType((*BodyDecommitUiTi)(nil), "signer.BodyDecommitUiTi")
	proto.RegisterType((*BodySi)(nil), "signer.BodySi")
}

func init() {
	proto.RegisterFile("github.com/getamis/alice/crypto/tss/signer/message.proto", fileDescriptor_ad801314df39a0f8)
}

var fileDescriptor_ad801314df39a0f8 = []byte{
	// 819 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x6e, 0xeb, 0x44,
	0x10, 0xb6, 0x1d, 0xc7, 0x4e, 0x26, 0xae, 0x6b, 0x16, 0xa8, 0x4c, 0x85, 0xaa, 0xd4, 0x95, 0x50,
	0xe1, 0xc2, 0x96, 0x8a, 0x40, 0x15, 0x42, 0xa0, 0xb4, 0x14, 0x19, 0x45, 0x55, 0x2b, 0xb7, 0xc0,
	0xb5, 0xe3, 0x2c, 0xc9, 0x2a, 0x89, 0x6d, 0xfc, 0x53, 0x14, 0x1e, 0x83, 0x07, 0x40, 0xe7, 0x01,
	0x7a, 0x75, 0x9e, 0xf0, 0x68, 0xd7, 0xeb, 0x78, 0x9d, 0x73, 0xaa, 0xf4, 0xe4, 0x72, 0x77, 0xbe,
	0x6f, 0x67, 0x32, 0xdf, 0x37, 0xe3, 0xc0, 0xe5, 0x8c, 0x14, 0xf3, 0x72, 0xe2, 0x46, 0xc9, 0xca,
	0x9b, 0xe1, 0x22, 0x5c, 0x91, 0xdc, 0x0b, 0x97, 0x24, 0xc2, 0x5e, 0x94, 0xad, 0xd3, 0x22, 0xf1,
	0x8a, 0x3c, 0xf7, 0x72, 0x32, 0x8b, 0x71, 0xe6, 0xad, 0x70, 0x9e, 0x87, 0x33, 0xec, 0xa6, 0x59,
	0x52, 0x24, 0x48, 0xab, 0x6e, 0x8f, 0x77, 0xbe, 0x10, 0x25, 0xab, 0x15, 0x29, 0x56, 0x38, 0x2e,
	0xda, 0x2f, 0x1c, 0x7f, 0xb7, 0x8b, 0xf9, 0xef, 0x22, 0xcd, 0x92, 0xe4, 0xaf, 0x2d, 0xda, 0xc5,
	0x2e, 0x5a, 0x92, 0x66, 0x5b, 0x1c, 0xe7, 0x6d, 0x17, 0xf4, 0xdb, 0xea, 0x06, 0x0d, 0x41, 0x2d,
	0xd6, 0x29, 0xb6, 0xe5, 0xa1, 0x7c, 0x6e, 0x5e, 0x18, 0x6e, 0xf5, 0x3b, 0xdc, 0xc7, 0x75, 0x8a,
	0x03, 0x16, 0x41, 0x26, 0x28, 0x64, 0x6a, 0x2b, 0x43, 0xf9, 0xbc, 0x1f, 0x28, 0x64, 0x8a, 0x3c,
	0xd0, 0xd2, 0x72, 0xb2, 0xc0, 0x6b, 0xbb, 0x33, 0x94, 0xcf, 0x07, 0x17, 0x9f, 0xd7, 0x9c, 0xab,
	0x64, 0xba, 0xbe, 0x2f, 0x27, 0x4b, 0x12, 0x8d, 0xf1, 0xda, 0x97, 0x02, 0x0e, 0x43, 0x5f, 0x81,
	0x8a, 0xe3, 0x68, 0x6c, 0xab, 0x0c, 0x6e, 0x89, 0xf0, 0x9b, 0x38, 0x1a, 0xfb, 0x52, 0xc0, 0xe2,
	0xe8, 0x0c, 0x3a, 0xab, 0x22, 0xb4, 0xbb, 0x0c, 0x76, 0x28, 0xc2, 0x6e, 0x8b, 0xd0, 0x97, 0x02,
	0x1a, 0x45, 0x5f, 0x43, 0x77, 0x8a, 0x97, 0x45, 0x68, 0x6b, 0x0c, 0xf6, 0x89, 0x08, 0xfb, 0x85,
	0x06, 0x7c, 0x29, 0xa8, 0x10, 0xc8, 0x03, 0x9d, 0x75, 0x6c, 0x44, 0x6c, 0x9d, 0x81, 0x3f, 0x6d,
	0x55, 0x5a, 0x85, 0x7c, 0x29, 0xa8, 0x51, 0xe8, 0x12, 0xa0, 0x92, 0xe7, 0x0f, 0x32, 0x22, 0x76,
	0x8f, 0x71, 0x8e, 0x44, 0xce, 0xf5, 0x26, 0xea, 0x4b, 0x81, 0x80, 0x45, 0x3f, 0x81, 0x31, 0xc5,
	0x02, 0xb7, 0xcf, 0xb8, 0x76, 0xbb, 0xb8, 0x48, 0x64, 0xb7, 0xf0, 0x4d, 0xe6, 0xdf, 0xc9, 0x23,
	0xb1, 0xe1, 0xa5, 0xcc, 0x34, 0xda, 0x64, 0xa6, 0x27, 0x31, 0x33, 0xe3, 0x0e, 0x5e, 0xce, 0xcc,
	0xd9, 0x2d, 0x3c, 0x1a, 0x82, 0x92, 0x13, 0xdb, 0x60, 0x2c, 0x53, 0x64, 0x3d, 0x50, 0xac, 0x92,
	0x13, 0xf4, 0x23, 0x0c, 0xa8, 0x87, 0x02, 0xfc, 0x77, 0x89, 0xf3, 0xc2, 0x3e, 0xe0, 0x09, 0xe8,
	0x9d, 0x7b, 0xd7, 0x04, 0xb8, 0xa1, 0x7c, 0x29, 0x10, 0xe1, 0xe8, 0x67, 0x30, 0xaa, 0x63, 0x9e,
	0x26, 0x71, 0x8e, 0x6d, 0x93, 0xd1, 0xbf, 0x10, 0xe9, 0x55, 0xa4, 0xe1, 0xb7, 0x08, 0x57, 0x1a,
	0xa8, 0x93, 0x64, 0xba, 0x76, 0x62, 0x38, 0x68, 0x19, 0x0c, 0x1d, 0x6d, 0x7c, 0x48, 0xbd, 0x6b,
	0x6c, 0xec, 0x76, 0x03, 0x46, 0x38, 0xbb, 0xde, 0x8c, 0x19, 0x77, 0xe9, 0xa9, 0xdb, 0x4c, 0x9e,
	0xeb, 0x87, 0xf9, 0xbc, 0x41, 0xf0, 0xcc, 0x41, 0x8b, 0xe6, 0x9c, 0x40, 0xaf, 0x76, 0x28, 0x42,
	0xcc, 0xc1, 0x0b, 0x36, 0x04, 0x06, 0x73, 0xeb, 0xc2, 0x89, 0x40, 0xe7, 0xd6, 0x44, 0x27, 0x00,
	0x38, 0x8e, 0x46, 0x64, 0xb4, 0x4c, 0xe7, 0x21, 0xaf, 0x46, 0xb8, 0xe1, 0xf1, 0x3f, 0x79, 0x5c,
	0xd9, 0xc4, 0xf9, 0x0d, 0xb2, 0x41, 0xff, 0x87, 0x30, 0x3f, 0xb2, 0x62, 0x8d, 0xa0, 0x3e, 0x3a,
	0xa7, 0xd0, 0xdf, 0x18, 0x1b, 0x7d, 0x56, 0x5b, 0xbf, 0xca, 0x50, 0x1d, 0x9c, 0xff, 0x64, 0x18,
	0x08, 0x7e, 0x46, 0x63, 0x30, 0xc3, 0x59, 0x2d, 0x39, 0x6b, 0x80, 0xcc, 0x1a, 0x70, 0xb6, 0xdd,
	0x00, 0x11, 0x53, 0xb7, 0x60, 0x8b, 0x8a, 0xbe, 0x07, 0x3d, 0xe4, 0x95, 0x29, 0xec, 0x95, 0x2f,
	0x5d, 0xbe, 0x86, 0xdc, 0x87, 0x68, 0x1e, 0x27, 0x59, 0xc6, 0x82, 0x35, 0xbd, 0x06, 0x3b, 0xff,
	0xcb, 0x60, 0xb6, 0x07, 0x86, 0xca, 0xf2, 0x44, 0xae, 0xb7, 0xab, 0x7a, 0x8d, 0x2c, 0x22, 0x8d,
	0xa9, 0x2b, 0x3e, 0xa3, 0xbc, 0x5e, 0x5d, 0x81, 0xe6, 0xbc, 0x51, 0xc0, 0xda, 0x9e, 0x4a, 0xda,
	0xba, 0x27, 0xb2, 0x77, 0xeb, 0xda, 0x54, 0xa6, 0x43, 0xfb, 0x31, 0xe5, 0x63, 0x74, 0x68, 0x3f,
	0xf6, 0x03, 0xf4, 0xb3, 0x79, 0xf2, 0x5b, 0xe3, 0x91, 0x5d, 0x4a, 0x34, 0x70, 0xaa, 0xe1, 0x92,
	0x6b, 0xa8, 0xbe, 0x46, 0xc3, 0xe5, 0x07, 0x35, 0x64, 0xcb, 0xe2, 0x06, 0x8c, 0x72, 0x3f, 0x0d,
	0xcb, 0x2d, 0x0d, 0x8b, 0xfd, 0x34, 0x14, 0x69, 0xce, 0xb3, 0xdc, 0xd6, 0x90, 0x95, 0x38, 0x06,
	0xb3, 0xdc, 0x5f, 0xc3, 0xf2, 0x3d, 0x0d, 0x8b, 0xfd, 0x35, 0x6c, 0x53, 0x1d, 0x1b, 0xb4, 0x6a,
	0xaf, 0xd2, 0x2f, 0x6a, 0x4e, 0xf8, 0x14, 0x2b, 0x39, 0xf9, 0xe6, 0x59, 0x06, 0x95, 0x7e, 0x70,
	0x11, 0x80, 0x76, 0xcf, 0x96, 0x98, 0x25, 0xa1, 0x1e, 0xa8, 0x74, 0xf7, 0x58, 0x32, 0xd2, 0xa1,
	0x73, 0x5b, 0x84, 0x96, 0x82, 0xfa, 0xd0, 0x65, 0x9b, 0xc0, 0xea, 0xa0, 0x01, 0xe8, 0x7c, 0xe0,
	0x2d, 0x15, 0x99, 0x00, 0xcd, 0xa0, 0x59, 0x5d, 0x64, 0x81, 0x21, 0xfa, 0xda, 0xd2, 0x1a, 0x04,
	0xed, 0x91, 0xa5, 0x8b, 0x08, 0x76, 0xd3, 0x43, 0x1a, 0x28, 0x0f, 0xc4, 0xea, 0xa3, 0x43, 0x18,
	0xdc, 0xdd, 0x07, 0xbf, 0xf2, 0xf5, 0x6d, 0x01, 0x85, 0x56, 0x17, 0xd5, 0x3e, 0xb6, 0x06, 0x13,
	0x8d, 0xfd, 0x8b, 0xf8, 0xf6, 0x5d, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x3c, 0xa1, 0x77, 0x2e,
	0x09, 0x00, 0x00,
}
