// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/getamis/alice/crypto/binaryquadraticform/message.proto

package binaryquadraticform

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BQForm struct {
	// a, b, c may be negative, so we use string type.
	A                    string   `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    string   `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	C                    string   `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BQForm) Reset()         { *m = BQForm{} }
func (m *BQForm) String() string { return proto.CompactTextString(m) }
func (*BQForm) ProtoMessage()    {}
func (*BQForm) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddba603057af8e31, []int{0}
}

func (m *BQForm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BQForm.Unmarshal(m, b)
}
func (m *BQForm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BQForm.Marshal(b, m, deterministic)
}
func (m *BQForm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BQForm.Merge(m, src)
}
func (m *BQForm) XXX_Size() int {
	return xxx_messageInfo_BQForm.Size(m)
}
func (m *BQForm) XXX_DiscardUnknown() {
	xxx_messageInfo_BQForm.DiscardUnknown(m)
}

var xxx_messageInfo_BQForm proto.InternalMessageInfo

func (m *BQForm) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *BQForm) GetB() string {
	if m != nil {
		return m.B
	}
	return ""
}

func (m *BQForm) GetC() string {
	if m != nil {
		return m.C
	}
	return ""
}

func init() {
	proto.RegisterType((*BQForm)(nil), "binaryquadraticform.BQForm")
}

func init() {
	proto.RegisterFile("github.com/getamis/alice/crypto/binaryquadraticform/message.proto", fileDescriptor_ddba603057af8e31)
}

var fileDescriptor_ddba603057af8e31 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x72, 0x4c, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x4f, 0x2d, 0x49, 0xcc, 0xcd, 0x2c, 0xd6, 0x4f,
	0xcc, 0xc9, 0x4c, 0x4e, 0xd5, 0x4f, 0x2e, 0xaa, 0x2c, 0x28, 0xc9, 0xd7, 0x4f, 0xca, 0xcc, 0x4b,
	0x2c, 0xaa, 0x2c, 0x2c, 0x4d, 0x4c, 0x29, 0x4a, 0x2c, 0xc9, 0x4c, 0x4e, 0xcb, 0x2f, 0xca, 0xd5,
	0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc6,
	0xa2, 0x44, 0xc9, 0x88, 0x8b, 0xcd, 0x29, 0xd0, 0x2d, 0xbf, 0x28, 0x57, 0x88, 0x87, 0x8b, 0x31,
	0x51, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x88, 0x31, 0x11, 0xc4, 0x4b, 0x92, 0x60, 0x82, 0xf0,
	0x92, 0x40, 0xbc, 0x64, 0x09, 0x66, 0x08, 0x2f, 0x39, 0x89, 0x0d, 0x6c, 0x9e, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x85, 0x17, 0x85, 0x4a, 0x94, 0x00, 0x00, 0x00,
}
