// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	types "github.com/getamis/alice/internal/message/types"
	mock "github.com/stretchr/testify/mock"
)

// StateChangedListener is an autogenerated mock type for the StateChangedListener type
type StateChangedListener struct {
	mock.Mock
}

// OnStateChanged provides a mock function with given fields: oldState, newState
func (_m *StateChangedListener) OnStateChanged(oldState types.MainState, newState types.MainState) {
	_m.Called(oldState, newState)
}
