// Code generated by mockery v2.49.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PeerManager is an autogenerated mock type for the PeerManager type
type PeerManager struct {
	mock.Mock
}

// MustSend provides a mock function with given fields: id, msg
func (_m *PeerManager) MustSend(id string, msg interface{}) {
	_m.Called(id, msg)
}

// NumPeers provides a mock function with given fields:
func (_m *PeerManager) NumPeers() uint32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NumPeers")
	}

	var r0 uint32
	if rf, ok := ret.Get(0).(func() uint32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint32)
	}

	return r0
}

// PeerIDs provides a mock function with given fields:
func (_m *PeerManager) PeerIDs() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PeerIDs")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// SelfID provides a mock function with given fields:
func (_m *PeerManager) SelfID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SelfID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewPeerManager creates a new instance of PeerManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPeerManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *PeerManager {
	mock := &PeerManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
