// Copyright © 2020 AMIS Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: github.com/getamis/alice/crypto/oprf/message.proto

package oprf

import (
	ecpointgrouplaw "github.com/getamis/alice/crypto/ecpointgrouplaw"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OprfRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alpha *ecpointgrouplaw.EcPointMessage `protobuf:"bytes,1,opt,name=alpha,proto3" json:"alpha,omitempty"`
}

func (x *OprfRequestMessage) Reset() {
	*x = OprfRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_getamis_alice_crypto_oprf_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OprfRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OprfRequestMessage) ProtoMessage() {}

func (x *OprfRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_getamis_alice_crypto_oprf_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OprfRequestMessage.ProtoReflect.Descriptor instead.
func (*OprfRequestMessage) Descriptor() ([]byte, []int) {
	return file_github_com_getamis_alice_crypto_oprf_message_proto_rawDescGZIP(), []int{0}
}

func (x *OprfRequestMessage) GetAlpha() *ecpointgrouplaw.EcPointMessage {
	if x != nil {
		return x.Alpha
	}
	return nil
}

type OprfResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beta *ecpointgrouplaw.EcPointMessage `protobuf:"bytes,1,opt,name=beta,proto3" json:"beta,omitempty"`
}

func (x *OprfResponseMessage) Reset() {
	*x = OprfResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_getamis_alice_crypto_oprf_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OprfResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OprfResponseMessage) ProtoMessage() {}

func (x *OprfResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_getamis_alice_crypto_oprf_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OprfResponseMessage.ProtoReflect.Descriptor instead.
func (*OprfResponseMessage) Descriptor() ([]byte, []int) {
	return file_github_com_getamis_alice_crypto_oprf_message_proto_rawDescGZIP(), []int{1}
}

func (x *OprfResponseMessage) GetBeta() *ecpointgrouplaw.EcPointMessage {
	if x != nil {
		return x.Beta
	}
	return nil
}

var File_github_com_getamis_alice_crypto_oprf_message_proto protoreflect.FileDescriptor

var file_github_com_getamis_alice_crypto_oprf_message_proto_rawDesc = []byte{
	0x0a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x74,
	0x61, 0x6d, 0x69, 0x73, 0x2f, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x2f, 0x6f, 0x70, 0x72, 0x66, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6f, 0x70, 0x72, 0x66, 0x1a, 0x3b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x74, 0x61, 0x6d, 0x69, 0x73, 0x2f, 0x61,
	0x6c, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f, 0x65, 0x63, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x6c, 0x61, 0x77, 0x2f, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x12, 0x4f, 0x70, 0x72, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a,
	0x05, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65,
	0x63, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x6c, 0x61, 0x77, 0x2e, 0x45,
	0x63, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x22, 0x4a, 0x0a, 0x13, 0x4f, 0x70, 0x72, 0x66, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x62,
	0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65, 0x63, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x6c, 0x61, 0x77, 0x2e, 0x45, 0x63, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x62, 0x65, 0x74, 0x61,
	0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x65, 0x74, 0x61, 0x6d, 0x69, 0x73, 0x2f, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x72, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_getamis_alice_crypto_oprf_message_proto_rawDescOnce sync.Once
	file_github_com_getamis_alice_crypto_oprf_message_proto_rawDescData = file_github_com_getamis_alice_crypto_oprf_message_proto_rawDesc
)

func file_github_com_getamis_alice_crypto_oprf_message_proto_rawDescGZIP() []byte {
	file_github_com_getamis_alice_crypto_oprf_message_proto_rawDescOnce.Do(func() {
		file_github_com_getamis_alice_crypto_oprf_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_getamis_alice_crypto_oprf_message_proto_rawDescData)
	})
	return file_github_com_getamis_alice_crypto_oprf_message_proto_rawDescData
}

var file_github_com_getamis_alice_crypto_oprf_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_getamis_alice_crypto_oprf_message_proto_goTypes = []interface{}{
	(*OprfRequestMessage)(nil),             // 0: oprf.OprfRequestMessage
	(*OprfResponseMessage)(nil),            // 1: oprf.OprfResponseMessage
	(*ecpointgrouplaw.EcPointMessage)(nil), // 2: ecpointgrouplaw.EcPointMessage
}
var file_github_com_getamis_alice_crypto_oprf_message_proto_depIdxs = []int32{
	2, // 0: oprf.OprfRequestMessage.alpha:type_name -> ecpointgrouplaw.EcPointMessage
	2, // 1: oprf.OprfResponseMessage.beta:type_name -> ecpointgrouplaw.EcPointMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_getamis_alice_crypto_oprf_message_proto_init() }
func file_github_com_getamis_alice_crypto_oprf_message_proto_init() {
	if File_github_com_getamis_alice_crypto_oprf_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_getamis_alice_crypto_oprf_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OprfRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_getamis_alice_crypto_oprf_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OprfResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_getamis_alice_crypto_oprf_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_getamis_alice_crypto_oprf_message_proto_goTypes,
		DependencyIndexes: file_github_com_getamis_alice_crypto_oprf_message_proto_depIdxs,
		MessageInfos:      file_github_com_getamis_alice_crypto_oprf_message_proto_msgTypes,
	}.Build()
	File_github_com_getamis_alice_crypto_oprf_message_proto = out.File
	file_github_com_getamis_alice_crypto_oprf_message_proto_rawDesc = nil
	file_github_com_getamis_alice_crypto_oprf_message_proto_goTypes = nil
	file_github_com_getamis_alice_crypto_oprf_message_proto_depIdxs = nil
}
