/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var github_com_getamis_alice_crypto_ecpointgrouplaw_point_pb = require('../../../../../github.com/getamis/alice/crypto/ecpointgrouplaw/point_pb.js');
goog.exportSymbol('proto.oprf.OprfRequestMessage', null, global);
goog.exportSymbol('proto.oprf.OprfResponseMessage', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.oprf.OprfRequestMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.oprf.OprfRequestMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.oprf.OprfRequestMessage.displayName = 'proto.oprf.OprfRequestMessage';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.oprf.OprfRequestMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.oprf.OprfRequestMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.oprf.OprfRequestMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oprf.OprfRequestMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    alpha: (f = msg.getAlpha()) && github_com_getamis_alice_crypto_ecpointgrouplaw_point_pb.EcPointMessage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.oprf.OprfRequestMessage}
 */
proto.oprf.OprfRequestMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.oprf.OprfRequestMessage;
  return proto.oprf.OprfRequestMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.oprf.OprfRequestMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.oprf.OprfRequestMessage}
 */
proto.oprf.OprfRequestMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new github_com_getamis_alice_crypto_ecpointgrouplaw_point_pb.EcPointMessage;
      reader.readMessage(value,github_com_getamis_alice_crypto_ecpointgrouplaw_point_pb.EcPointMessage.deserializeBinaryFromReader);
      msg.setAlpha(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.oprf.OprfRequestMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.oprf.OprfRequestMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.oprf.OprfRequestMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oprf.OprfRequestMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAlpha();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      github_com_getamis_alice_crypto_ecpointgrouplaw_point_pb.EcPointMessage.serializeBinaryToWriter
    );
  }
};


/**
 * optional ecpointgrouplaw.EcPointMessage alpha = 1;
 * @return {?proto.ecpointgrouplaw.EcPointMessage}
 */
proto.oprf.OprfRequestMessage.prototype.getAlpha = function() {
  return /** @type{?proto.ecpointgrouplaw.EcPointMessage} */ (
    jspb.Message.getWrapperField(this, github_com_getamis_alice_crypto_ecpointgrouplaw_point_pb.EcPointMessage, 1));
};


/** @param {?proto.ecpointgrouplaw.EcPointMessage|undefined} value */
proto.oprf.OprfRequestMessage.prototype.setAlpha = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.oprf.OprfRequestMessage.prototype.clearAlpha = function() {
  this.setAlpha(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.oprf.OprfRequestMessage.prototype.hasAlpha = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.oprf.OprfResponseMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.oprf.OprfResponseMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.oprf.OprfResponseMessage.displayName = 'proto.oprf.OprfResponseMessage';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.oprf.OprfResponseMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.oprf.OprfResponseMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.oprf.OprfResponseMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oprf.OprfResponseMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    beta: (f = msg.getBeta()) && github_com_getamis_alice_crypto_ecpointgrouplaw_point_pb.EcPointMessage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.oprf.OprfResponseMessage}
 */
proto.oprf.OprfResponseMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.oprf.OprfResponseMessage;
  return proto.oprf.OprfResponseMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.oprf.OprfResponseMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.oprf.OprfResponseMessage}
 */
proto.oprf.OprfResponseMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new github_com_getamis_alice_crypto_ecpointgrouplaw_point_pb.EcPointMessage;
      reader.readMessage(value,github_com_getamis_alice_crypto_ecpointgrouplaw_point_pb.EcPointMessage.deserializeBinaryFromReader);
      msg.setBeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.oprf.OprfResponseMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.oprf.OprfResponseMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.oprf.OprfResponseMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oprf.OprfResponseMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBeta();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      github_com_getamis_alice_crypto_ecpointgrouplaw_point_pb.EcPointMessage.serializeBinaryToWriter
    );
  }
};


/**
 * optional ecpointgrouplaw.EcPointMessage beta = 1;
 * @return {?proto.ecpointgrouplaw.EcPointMessage}
 */
proto.oprf.OprfResponseMessage.prototype.getBeta = function() {
  return /** @type{?proto.ecpointgrouplaw.EcPointMessage} */ (
    jspb.Message.getWrapperField(this, github_com_getamis_alice_crypto_ecpointgrouplaw_point_pb.EcPointMessage, 1));
};


/** @param {?proto.ecpointgrouplaw.EcPointMessage|undefined} value */
proto.oprf.OprfResponseMessage.prototype.setBeta = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.oprf.OprfResponseMessage.prototype.clearBeta = function() {
  this.setBeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.oprf.OprfResponseMessage.prototype.hasBeta = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.oprf);
