// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/getamis/alice/crypto/commitment/message.proto

package commitment

import (
	fmt "fmt"
	ecpointgrouplaw "github.com/getamis/alice/crypto/ecpointgrouplaw"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// HashCommitmentMessage and HashDecommitmentMessage are for HashCommitment
// HashCommitmentMessage contains the blake2b initial vector and data digest for commitment use
type HashCommitmentMessage struct {
	Digest               []byte   `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashCommitmentMessage) Reset()         { *m = HashCommitmentMessage{} }
func (m *HashCommitmentMessage) String() string { return proto.CompactTextString(m) }
func (*HashCommitmentMessage) ProtoMessage()    {}
func (*HashCommitmentMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d785704ceb4dbe, []int{0}
}

func (m *HashCommitmentMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashCommitmentMessage.Unmarshal(m, b)
}
func (m *HashCommitmentMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashCommitmentMessage.Marshal(b, m, deterministic)
}
func (m *HashCommitmentMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashCommitmentMessage.Merge(m, src)
}
func (m *HashCommitmentMessage) XXX_Size() int {
	return xxx_messageInfo_HashCommitmentMessage.Size(m)
}
func (m *HashCommitmentMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HashCommitmentMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HashCommitmentMessage proto.InternalMessageInfo

func (m *HashCommitmentMessage) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

// HashDecommitmentMessage contains original data and salt for decommitment use
type HashDecommitmentMessage struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Salt                 []byte   `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashDecommitmentMessage) Reset()         { *m = HashDecommitmentMessage{} }
func (m *HashDecommitmentMessage) String() string { return proto.CompactTextString(m) }
func (*HashDecommitmentMessage) ProtoMessage()    {}
func (*HashDecommitmentMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d785704ceb4dbe, []int{1}
}

func (m *HashDecommitmentMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashDecommitmentMessage.Unmarshal(m, b)
}
func (m *HashDecommitmentMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashDecommitmentMessage.Marshal(b, m, deterministic)
}
func (m *HashDecommitmentMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashDecommitmentMessage.Merge(m, src)
}
func (m *HashDecommitmentMessage) XXX_Size() int {
	return xxx_messageInfo_HashDecommitmentMessage.Size(m)
}
func (m *HashDecommitmentMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HashDecommitmentMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HashDecommitmentMessage proto.InternalMessageInfo

func (m *HashDecommitmentMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *HashDecommitmentMessage) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

// PointCommitmentMessage and PointDecommitmentMessage are for PointDecommitment
// PointCommitmentMessage contains rank and its points for commitment use
type PointCommitmentMessage struct {
	Points               []*ecpointgrouplaw.EcPointMessage `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *PointCommitmentMessage) Reset()         { *m = PointCommitmentMessage{} }
func (m *PointCommitmentMessage) String() string { return proto.CompactTextString(m) }
func (*PointCommitmentMessage) ProtoMessage()    {}
func (*PointCommitmentMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d785704ceb4dbe, []int{2}
}

func (m *PointCommitmentMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointCommitmentMessage.Unmarshal(m, b)
}
func (m *PointCommitmentMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointCommitmentMessage.Marshal(b, m, deterministic)
}
func (m *PointCommitmentMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointCommitmentMessage.Merge(m, src)
}
func (m *PointCommitmentMessage) XXX_Size() int {
	return xxx_messageInfo_PointCommitmentMessage.Size(m)
}
func (m *PointCommitmentMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PointCommitmentMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PointCommitmentMessage proto.InternalMessageInfo

func (m *PointCommitmentMessage) GetPoints() []*ecpointgrouplaw.EcPointMessage {
	if m != nil {
		return m.Points
	}
	return nil
}

// FeldmanVerifyMessage contains evaluation for verification use
type FeldmanVerifyMessage struct {
	Evaluation           []byte   `protobuf:"bytes,1,opt,name=evaluation,proto3" json:"evaluation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeldmanVerifyMessage) Reset()         { *m = FeldmanVerifyMessage{} }
func (m *FeldmanVerifyMessage) String() string { return proto.CompactTextString(m) }
func (*FeldmanVerifyMessage) ProtoMessage()    {}
func (*FeldmanVerifyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d785704ceb4dbe, []int{3}
}

func (m *FeldmanVerifyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeldmanVerifyMessage.Unmarshal(m, b)
}
func (m *FeldmanVerifyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeldmanVerifyMessage.Marshal(b, m, deterministic)
}
func (m *FeldmanVerifyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeldmanVerifyMessage.Merge(m, src)
}
func (m *FeldmanVerifyMessage) XXX_Size() int {
	return xxx_messageInfo_FeldmanVerifyMessage.Size(m)
}
func (m *FeldmanVerifyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FeldmanVerifyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FeldmanVerifyMessage proto.InternalMessageInfo

func (m *FeldmanVerifyMessage) GetEvaluation() []byte {
	if m != nil {
		return m.Evaluation
	}
	return nil
}

// PedersenVerifyMessage contains evaluation and salt for verification use
type PedersenVerifyMessage struct {
	Evaluation           []byte   `protobuf:"bytes,1,opt,name=evaluation,proto3" json:"evaluation,omitempty"`
	Salt                 []byte   `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PedersenVerifyMessage) Reset()         { *m = PedersenVerifyMessage{} }
func (m *PedersenVerifyMessage) String() string { return proto.CompactTextString(m) }
func (*PedersenVerifyMessage) ProtoMessage()    {}
func (*PedersenVerifyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d785704ceb4dbe, []int{4}
}

func (m *PedersenVerifyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PedersenVerifyMessage.Unmarshal(m, b)
}
func (m *PedersenVerifyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PedersenVerifyMessage.Marshal(b, m, deterministic)
}
func (m *PedersenVerifyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PedersenVerifyMessage.Merge(m, src)
}
func (m *PedersenVerifyMessage) XXX_Size() int {
	return xxx_messageInfo_PedersenVerifyMessage.Size(m)
}
func (m *PedersenVerifyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PedersenVerifyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PedersenVerifyMessage proto.InternalMessageInfo

func (m *PedersenVerifyMessage) GetEvaluation() []byte {
	if m != nil {
		return m.Evaluation
	}
	return nil
}

func (m *PedersenVerifyMessage) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func init() {
	proto.RegisterType((*HashCommitmentMessage)(nil), "commitment.HashCommitmentMessage")
	proto.RegisterType((*HashDecommitmentMessage)(nil), "commitment.HashDecommitmentMessage")
	proto.RegisterType((*PointCommitmentMessage)(nil), "commitment.PointCommitmentMessage")
	proto.RegisterType((*FeldmanVerifyMessage)(nil), "commitment.FeldmanVerifyMessage")
	proto.RegisterType((*PedersenVerifyMessage)(nil), "commitment.PedersenVerifyMessage")
}

func init() {
	proto.RegisterFile("github.com/getamis/alice/crypto/commitment/message.proto", fileDescriptor_17d785704ceb4dbe)
}

var fileDescriptor_17d785704ceb4dbe = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xcd, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xa9, 0xca, 0x1e, 0x46, 0x4f, 0x8b, 0xad, 0x8b, 0x07, 0x2d, 0x7b, 0xea, 0x69, 0x03,
	0x0a, 0x2a, 0x78, 0x12, 0x3f, 0x10, 0x44, 0xa8, 0x3d, 0x78, 0x9f, 0x66, 0xc7, 0x34, 0x90, 0x6c,
	0x96, 0x64, 0x56, 0xe9, 0x7f, 0x2f, 0x9b, 0x8d, 0x1f, 0x58, 0x41, 0xbc, 0xcd, 0xbc, 0xe4, 0xf7,
	0xde, 0x4b, 0xe0, 0x42, 0x69, 0x5e, 0x75, 0xcb, 0x4a, 0x3a, 0x2b, 0x14, 0x31, 0x5a, 0x1d, 0x04,
	0x1a, 0x2d, 0x49, 0x48, 0xbf, 0x6e, 0xd9, 0x09, 0xe9, 0xac, 0xd5, 0x6c, 0xa9, 0x61, 0x61, 0x29,
	0x04, 0x54, 0x54, 0xb5, 0xde, 0xb1, 0xcb, 0xe1, 0xeb, 0xe4, 0xf0, 0xf2, 0x2f, 0x17, 0x92, 0xad,
	0xd3, 0x0d, 0x2b, 0xef, 0xba, 0xd6, 0xe0, 0x9b, 0x88, 0xdb, 0x60, 0x54, 0x0a, 0x18, 0xdf, 0x63,
	0x58, 0x5d, 0x7f, 0xda, 0x3d, 0x0e, 0x39, 0xf9, 0x04, 0xb2, 0x5a, 0x2b, 0x0a, 0x5c, 0x8c, 0xa6,
	0xa3, 0xd9, 0xde, 0x22, 0x6d, 0xe5, 0x15, 0x1c, 0xf4, 0xc0, 0x0d, 0xc9, 0x0d, 0x24, 0x87, 0x9d,
	0x1a, 0x19, 0x13, 0x10, 0xe7, 0x5e, 0x0b, 0x68, 0xb8, 0xd8, 0x1a, 0xb4, 0x7e, 0x2e, 0x9f, 0x60,
	0x32, 0xef, 0x2b, 0x6c, 0x86, 0x9e, 0x43, 0x16, 0xcb, 0x85, 0x62, 0x34, 0xdd, 0x9e, 0xed, 0x9e,
	0x1c, 0x57, 0x3f, 0xba, 0x57, 0xb7, 0x32, 0xa2, 0x09, 0x58, 0xa4, 0xeb, 0xe5, 0x19, 0xec, 0xdf,
	0x91, 0xa9, 0x2d, 0x36, 0xcf, 0xe4, 0xf5, 0xcb, 0xfa, 0xc3, 0xf0, 0x08, 0x80, 0x5e, 0xd1, 0x74,
	0xc8, 0xda, 0x35, 0xa9, 0xd8, 0x37, 0xa5, 0x7c, 0x80, 0xf1, 0x9c, 0x6a, 0xf2, 0x81, 0xfe, 0x07,
	0xfe, 0xf6, 0xae, 0x65, 0x16, 0xbf, 0xf4, 0xf4, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xf7, 0x2c,
	0xa7, 0xd7, 0x01, 0x00, 0x00,
}
