// Copyright © 2025 AMIS Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: github.com/getamis/alice/crypto/tss/bls/message.proto

package bls

import (
	birkhoffinterpolation "github.com/getamis/alice/crypto/birkhoffinterpolation"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature []byte                                    `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey []byte                                    `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Bk        *birkhoffinterpolation.BkParameterMessage `protobuf:"bytes,3,opt,name=bk,proto3" json:"bk,omitempty"`
}

func (x *SignMessage) Reset() {
	*x = SignMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_getamis_alice_crypto_tss_bls_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessage) ProtoMessage() {}

func (x *SignMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_getamis_alice_crypto_tss_bls_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessage.ProtoReflect.Descriptor instead.
func (*SignMessage) Descriptor() ([]byte, []int) {
	return file_github_com_getamis_alice_crypto_tss_bls_message_proto_rawDescGZIP(), []int{0}
}

func (x *SignMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignMessage) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SignMessage) GetBk() *birkhoffinterpolation.BkParameterMessage {
	if x != nil {
		return x.Bk
	}
	return nil
}

type ShareValidationMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartialPubKey []byte                                    `protobuf:"bytes,1,opt,name=partialPubKey,proto3" json:"partialPubKey,omitempty"`
	PublicKey     []byte                                    `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Bk            *birkhoffinterpolation.BkParameterMessage `protobuf:"bytes,3,opt,name=bk,proto3" json:"bk,omitempty"`
	Proof         *SchnorrProofG1Message                    `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *ShareValidationMessage) Reset() {
	*x = ShareValidationMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_getamis_alice_crypto_tss_bls_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareValidationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareValidationMessage) ProtoMessage() {}

func (x *ShareValidationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_getamis_alice_crypto_tss_bls_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareValidationMessage.ProtoReflect.Descriptor instead.
func (*ShareValidationMessage) Descriptor() ([]byte, []int) {
	return file_github_com_getamis_alice_crypto_tss_bls_message_proto_rawDescGZIP(), []int{1}
}

func (x *ShareValidationMessage) GetPartialPubKey() []byte {
	if x != nil {
		return x.PartialPubKey
	}
	return nil
}

func (x *ShareValidationMessage) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ShareValidationMessage) GetBk() *birkhoffinterpolation.BkParameterMessage {
	if x != nil {
		return x.Bk
	}
	return nil
}

func (x *ShareValidationMessage) GetProof() *SchnorrProofG1Message {
	if x != nil {
		return x.Proof
	}
	return nil
}

type SchnorrProofG1Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Salt   []byte `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	V      []byte `protobuf:"bytes,2,opt,name=V,proto3" json:"V,omitempty"`
	R      []byte `protobuf:"bytes,3,opt,name=r,proto3" json:"r,omitempty"`
	AuxMsg []byte `protobuf:"bytes,4,opt,name=auxMsg,proto3" json:"auxMsg,omitempty"`
}

func (x *SchnorrProofG1Message) Reset() {
	*x = SchnorrProofG1Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_getamis_alice_crypto_tss_bls_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchnorrProofG1Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchnorrProofG1Message) ProtoMessage() {}

func (x *SchnorrProofG1Message) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_getamis_alice_crypto_tss_bls_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchnorrProofG1Message.ProtoReflect.Descriptor instead.
func (*SchnorrProofG1Message) Descriptor() ([]byte, []int) {
	return file_github_com_getamis_alice_crypto_tss_bls_message_proto_rawDescGZIP(), []int{2}
}

func (x *SchnorrProofG1Message) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *SchnorrProofG1Message) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *SchnorrProofG1Message) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *SchnorrProofG1Message) GetAuxMsg() []byte {
	if x != nil {
		return x.AuxMsg
	}
	return nil
}

var File_github_com_getamis_alice_crypto_tss_bls_message_proto protoreflect.FileDescriptor

var file_github_com_getamis_alice_crypto_tss_bls_message_proto_rawDesc = []byte{
	0x0a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x74,
	0x61, 0x6d, 0x69, 0x73, 0x2f, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x2f, 0x74, 0x73, 0x73, 0x2f, 0x62, 0x6c, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x67, 0x65, 0x74, 0x61, 0x6d, 0x69, 0x73,
	0x2e, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x62, 0x6c,
	0x73, 0x6d, 0x70, 0x63, 0x1a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x65, 0x74, 0x61, 0x6d, 0x69, 0x73, 0x2f, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x2f, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f, 0x62, 0x69, 0x72, 0x6b, 0x68, 0x6f, 0x66, 0x66, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x62, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99, 0x01, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x12, 0x4e, 0x0a, 0x02, 0x62, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x67,
	0x65, 0x74, 0x61, 0x6d, 0x69, 0x73, 0x2e, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x6f, 0x2e, 0x62, 0x69, 0x72, 0x6b, 0x68, 0x6f, 0x66, 0x66, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6b, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x02, 0x62, 0x6b,
	0x22, 0xf6, 0x01, 0x0a, 0x16, 0x53, 0x68, 0x61, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x70,
	0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x4b, 0x65,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12,
	0x4e, 0x0a, 0x02, 0x62, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x67, 0x65,
	0x74, 0x61, 0x6d, 0x69, 0x73, 0x2e, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x2e, 0x62, 0x69, 0x72, 0x6b, 0x68, 0x6f, 0x66, 0x66, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x70, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x02, 0x62, 0x6b, 0x12,
	0x48, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32,
	0x2e, 0x67, 0x65, 0x74, 0x61, 0x6d, 0x69, 0x73, 0x2e, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x2e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x62, 0x6c, 0x73, 0x6d, 0x70, 0x63, 0x2e, 0x53, 0x63, 0x68,
	0x6e, 0x6f, 0x72, 0x72, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x47, 0x31, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x5f, 0x0a, 0x15, 0x53, 0x63, 0x68,
	0x6e, 0x6f, 0x72, 0x72, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x47, 0x31, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x56, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x01, 0x56, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x01, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x78, 0x4d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x61, 0x75, 0x78, 0x4d, 0x73, 0x67, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x74, 0x61, 0x6d, 0x69, 0x73,
	0x2f, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f, 0x74, 0x73,
	0x73, 0x2f, 0x62, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_getamis_alice_crypto_tss_bls_message_proto_rawDescOnce sync.Once
	file_github_com_getamis_alice_crypto_tss_bls_message_proto_rawDescData = file_github_com_getamis_alice_crypto_tss_bls_message_proto_rawDesc
)

func file_github_com_getamis_alice_crypto_tss_bls_message_proto_rawDescGZIP() []byte {
	file_github_com_getamis_alice_crypto_tss_bls_message_proto_rawDescOnce.Do(func() {
		file_github_com_getamis_alice_crypto_tss_bls_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_getamis_alice_crypto_tss_bls_message_proto_rawDescData)
	})
	return file_github_com_getamis_alice_crypto_tss_bls_message_proto_rawDescData
}

var file_github_com_getamis_alice_crypto_tss_bls_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_getamis_alice_crypto_tss_bls_message_proto_goTypes = []interface{}{
	(*SignMessage)(nil),                              // 0: getamis.alice.crypto.blsmpc.SignMessage
	(*ShareValidationMessage)(nil),                   // 1: getamis.alice.crypto.blsmpc.ShareValidationMessage
	(*SchnorrProofG1Message)(nil),                    // 2: getamis.alice.crypto.blsmpc.SchnorrProofG1Message
	(*birkhoffinterpolation.BkParameterMessage)(nil), // 3: getamis.alice.crypto.birkhoffinterpolation.BkParameterMessage
}
var file_github_com_getamis_alice_crypto_tss_bls_message_proto_depIdxs = []int32{
	3, // 0: getamis.alice.crypto.blsmpc.SignMessage.bk:type_name -> getamis.alice.crypto.birkhoffinterpolation.BkParameterMessage
	3, // 1: getamis.alice.crypto.blsmpc.ShareValidationMessage.bk:type_name -> getamis.alice.crypto.birkhoffinterpolation.BkParameterMessage
	2, // 2: getamis.alice.crypto.blsmpc.ShareValidationMessage.proof:type_name -> getamis.alice.crypto.blsmpc.SchnorrProofG1Message
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_getamis_alice_crypto_tss_bls_message_proto_init() }
func file_github_com_getamis_alice_crypto_tss_bls_message_proto_init() {
	if File_github_com_getamis_alice_crypto_tss_bls_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_getamis_alice_crypto_tss_bls_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_getamis_alice_crypto_tss_bls_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareValidationMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_getamis_alice_crypto_tss_bls_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchnorrProofG1Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_getamis_alice_crypto_tss_bls_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_getamis_alice_crypto_tss_bls_message_proto_goTypes,
		DependencyIndexes: file_github_com_getamis_alice_crypto_tss_bls_message_proto_depIdxs,
		MessageInfos:      file_github_com_getamis_alice_crypto_tss_bls_message_proto_msgTypes,
	}.Build()
	File_github_com_getamis_alice_crypto_tss_bls_message_proto = out.File
	file_github_com_getamis_alice_crypto_tss_bls_message_proto_rawDesc = nil
	file_github_com_getamis_alice_crypto_tss_bls_message_proto_goTypes = nil
	file_github_com_getamis_alice_crypto_tss_bls_message_proto_depIdxs = nil
}
