/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var github_com_getamis_alice_crypto_zkproof_message_pb = require('../../../../../../github.com/getamis/alice/crypto/zkproof/message_pb.js');
goog.exportSymbol('proto.paillier.PubKeyMessage', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.paillier.PubKeyMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.paillier.PubKeyMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.paillier.PubKeyMessage.displayName = 'proto.paillier.PubKeyMessage';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.paillier.PubKeyMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.paillier.PubKeyMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.paillier.PubKeyMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.paillier.PubKeyMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    proof: (f = msg.getProof()) && github_com_getamis_alice_crypto_zkproof_message_pb.IntegerFactorizationProofMessage.toObject(includeInstance, f),
    g: msg.getG_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.paillier.PubKeyMessage}
 */
proto.paillier.PubKeyMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.paillier.PubKeyMessage;
  return proto.paillier.PubKeyMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.paillier.PubKeyMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.paillier.PubKeyMessage}
 */
proto.paillier.PubKeyMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new github_com_getamis_alice_crypto_zkproof_message_pb.IntegerFactorizationProofMessage;
      reader.readMessage(value,github_com_getamis_alice_crypto_zkproof_message_pb.IntegerFactorizationProofMessage.deserializeBinaryFromReader);
      msg.setProof(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setG(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.paillier.PubKeyMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.paillier.PubKeyMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.paillier.PubKeyMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.paillier.PubKeyMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProof();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      github_com_getamis_alice_crypto_zkproof_message_pb.IntegerFactorizationProofMessage.serializeBinaryToWriter
    );
  }
  f = message.getG_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional zkproof.IntegerFactorizationProofMessage proof = 1;
 * @return {?proto.zkproof.IntegerFactorizationProofMessage}
 */
proto.paillier.PubKeyMessage.prototype.getProof = function() {
  return /** @type{?proto.zkproof.IntegerFactorizationProofMessage} */ (
    jspb.Message.getWrapperField(this, github_com_getamis_alice_crypto_zkproof_message_pb.IntegerFactorizationProofMessage, 1));
};


/** @param {?proto.zkproof.IntegerFactorizationProofMessage|undefined} value */
proto.paillier.PubKeyMessage.prototype.setProof = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.paillier.PubKeyMessage.prototype.clearProof = function() {
  this.setProof(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.paillier.PubKeyMessage.prototype.hasProof = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes g = 2;
 * @return {!(string|Uint8Array)}
 */
proto.paillier.PubKeyMessage.prototype.getG = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes g = 2;
 * This is a type-conversion wrapper around `getG()`
 * @return {string}
 */
proto.paillier.PubKeyMessage.prototype.getG_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getG()));
};


/**
 * optional bytes g = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getG()`
 * @return {!Uint8Array}
 */
proto.paillier.PubKeyMessage.prototype.getG_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getG()));
};


/** @param {!(string|Uint8Array)} value */
proto.paillier.PubKeyMessage.prototype.setG = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


goog.object.extend(exports, proto.paillier);
